# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'install stunnel'
        run: |
          choco install -y stunnel --force
        shell: cmd
      - uses: msys2/setup-msys2@ddf331adaebd714795f1042345e6ca57bd66cea8 # v2
        with:
          msystem: 'msys'

      - name: 'install stunnel'
        run: |
          export PATH="$PATH:/c/Program Files (x86)/stunnel/bin"
          echo $PATH
          stunnel
        shell: msys2 {0}

      - name: 'install stunnel'
        run: |
          export PATH="$PATH:/c/Program Files (x86)/stunnel/bin"
          echo $PATH
          stunnel
        shell: bash
